// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: cloud.signaling.proto

package signalingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAnswerReq 获取answer请求
type GetAnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Sdp   string `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *GetAnswerReq) Reset() {
	*x = GetAnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_signaling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerReq) ProtoMessage() {}

func (x *GetAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_signaling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerReq.ProtoReflect.Descriptor instead.
func (*GetAnswerReq) Descriptor() ([]byte, []int) {
	return file_cloud_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *GetAnswerReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAnswerReq) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// GetAnswerResp 获取answer响应
type GetAnswerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdp string `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
}

func (x *GetAnswerResp) Reset() {
	*x = GetAnswerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_signaling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnswerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerResp) ProtoMessage() {}

func (x *GetAnswerResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_signaling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerResp.ProtoReflect.Descriptor instead.
func (*GetAnswerResp) Descriptor() ([]byte, []int) {
	return file_cloud_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnswerResp) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// AuthPeerReq 认证请求
type AuthPeerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     string `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret string `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
}

func (x *AuthPeerReq) Reset() {
	*x = AuthPeerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_signaling_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthPeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPeerReq) ProtoMessage() {}

func (x *AuthPeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_signaling_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPeerReq.ProtoReflect.Descriptor instead.
func (*AuthPeerReq) Descriptor() ([]byte, []int) {
	return file_cloud_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *AuthPeerReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AuthPeerReq) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

// AuthPeerResp 认证响应
type AuthPeerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *AuthPeerResp) Reset() {
	*x = AuthPeerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_signaling_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthPeerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPeerResp) ProtoMessage() {}

func (x *AuthPeerResp) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_signaling_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPeerResp.ProtoReflect.Descriptor instead.
func (*AuthPeerResp) Descriptor() ([]byte, []int) {
	return file_cloud_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *AuthPeerResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_cloud_signaling_proto protoreflect.FileDescriptor

var file_cloud_signaling_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x22, 0x21, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x64, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x64, 0x70, 0x22, 0x41, 0x0a,
	0x0b, 0x41, 0x75, 0x74, 0x68, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x22, 0x1e, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x32, 0x3f, 0x0a, 0x0b, 0x70, 0x65, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x30, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x32, 0x44, 0x0a, 0x13, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x50, 0x65, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_signaling_proto_rawDescOnce sync.Once
	file_cloud_signaling_proto_rawDescData = file_cloud_signaling_proto_rawDesc
)

func file_cloud_signaling_proto_rawDescGZIP() []byte {
	file_cloud_signaling_proto_rawDescOnce.Do(func() {
		file_cloud_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_signaling_proto_rawDescData)
	})
	return file_cloud_signaling_proto_rawDescData
}

var file_cloud_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cloud_signaling_proto_goTypes = []interface{}{
	(*GetAnswerReq)(nil),  // 0: pb.GetAnswerReq
	(*GetAnswerResp)(nil), // 1: pb.GetAnswerResp
	(*AuthPeerReq)(nil),   // 2: pb.AuthPeerReq
	(*AuthPeerResp)(nil),  // 3: pb.AuthPeerResp
}
var file_cloud_signaling_proto_depIdxs = []int32{
	0, // 0: pb.peerService.GetAnswer:input_type -> pb.GetAnswerReq
	2, // 1: pb.internalAuthService.AuthPeer:input_type -> pb.AuthPeerReq
	1, // 2: pb.peerService.GetAnswer:output_type -> pb.GetAnswerResp
	3, // 3: pb.internalAuthService.AuthPeer:output_type -> pb.AuthPeerResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cloud_signaling_proto_init() }
func file_cloud_signaling_proto_init() {
	if File_cloud_signaling_proto != nil {
		return
	}
	file_types_signaling_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cloud_signaling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_signaling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnswerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_signaling_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthPeerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_signaling_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthPeerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_signaling_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cloud_signaling_proto_goTypes,
		DependencyIndexes: file_cloud_signaling_proto_depIdxs,
		MessageInfos:      file_cloud_signaling_proto_msgTypes,
	}.Build()
	File_cloud_signaling_proto = out.File
	file_cloud_signaling_proto_rawDesc = nil
	file_cloud_signaling_proto_goTypes = nil
	file_cloud_signaling_proto_depIdxs = nil
}
